name: orbit
description: TLE and NORAD SGP4/SDP4/SGP8/SDP8 Implementation for Dart and Flutter.
version: 0.0.5
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_orbit

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  latlng: ^1.0.0

dev_dependencies:
  test: ^1.22.0
  lints: ^3.0.0
